### PR TITLE
Support of "flattened data structure" with multiple top-level schemas per collection

### PR DESCRIPTION
**Pull request by newsiberian**
Hello, here are some changes, which add a support of **flattened data structures** to collection2.

Here is an example:

```
Product = new SimpleSchema({
  _id: {
    type: String,
    optional: true
  },
  title: {
    type: String,
    defaultValue: ""
  },
  type: {
    label: "Type",
    type: String,
    defaultValue: "simple"
  },
  description: {
    type: String,
    defaultValue: "This is a simple product."
  }
});

ProductVariant = new SimpleSchema({
  _id: {
    type: String,
    optional: true
  },
  title: {
    type: String,
    defaultValue: ""
  },
  optionTitle: {
    label: "Option",
    type: String,
    optional: true
  },
  type: {
    label: "Type",
    type: String,
    defaultValue: "variant"
  },
  price: {
    label: "Price",
    type: Number,
    decimal: true,
    min: 0,
    optional: true,
    defaultValue: 5
  }
});
```
To use these schemas on the top level in one collection we can do the following:

```
products = new Mongo.Collection("Products");

products.attachSchema([
    { schema: Product, selector: { type: 'simple' }},
    { schema: ProductVariant, selector: { type: 'variant' }}
  ], { multiple: true }
);
```

where `type` is a selector as you can see.

`insert`, `update`, `upsert` operation could be done by the following syntax:

```
var productId = products.insert({ title: 'Product one' }, { selector: { type: 'simple' } });

products.update(productId, {
        $set: { title: 'New product one' }
      }, { selector: { type: 'simple' } });

products.upsert({ title: 'New product one', type: 'simple' },
        { $set: { description: 'This is a modified product one.' }},
        { selector: { type: 'simple' } }
);
```
This could affect on #257, #208, #235

### CODE REVIEW

**Comment by aldeed** [comment]
@newsiberian Thanks, this is good but I'm not sure I like the API. You can already call attachSchema multiple times. By default it merges. So how about there is just a `name` option and then a `schema` option when calling insert/update?

```js
products.attachSchema(Product, {name: 'Product'});
products.attachSchema(ProductVariant, {name: 'ProductVariant', selector: selector});
```

The presence of `name` option will automatically imply `multiple:true`.

And then:

```js
// By name
products.update(productId, {$set: { title: 'New product one' }}, { schema: 'Product' });
// Or chosen automatically by selector
products.update(productId, {$set: { title: 'New product one', type: 'simple' }});
```

However, I don't see how the `schema` option can possibly work on the client since options aren't available in the `deny` function. Choosing based on a selector can work. But even if this cannot all be implemented, it may be possible with the new ValidatedCollection, which is going to pretty much replace Collection2. So it is worth pursuing.

**Comment by newsiberian** [comment]
@aldeed, thanks for response. It's good to hear about new ValidatedCollection), but before I begin to look deeply into your requests, I want explain more about why was chosen such method by pushing few schemas by one in an array.

The problem in current possibility to attach multiple schemas is in fact that they are merging into one big schema. This completely brokes all the logic of the `flattened data structure` where we could have several top-level schemas with the same-called properties, like property `type` in our example which has a different `defaultValue` for different types of objects (category, product, variant). And the second big problem with merged schema is that it will use all props with `defaultValue` from all schemas to one type of validated object. For example, when inserting `product`, it also will apply all `defaultValue` from `variant` and other schemas. 
This is the reason why I push all schemas into one array, to keep them separately inside collection2.

Any thoughts on this?

**Comment by aldeed** [comment]
@newsiberian I understand that they need to be stored internally separately in an array, but I don't think they need to be passed as an array, and the `multiple: true` option isn't necessary. I think it would add confusion with passing in multiple and having them merged.

I also don't think we need `name` prop as I proposed for now. So I would propose that it accept only a single schema and if the `selector` option is present, then store it in `_simpleSchemas` array.

```js
products.attachSchema(Product, {selector: {type: 'simple'}});
products.attachSchema(ProductVariant, {selector: {type: 'variant'}});
```

Another problem with this is that you don't currently handle the case where we're validating a modifier. In order for this to work properly with updates, I think we'd have to add in a `findOne` to get the current document and check it against the selector. But then it would also have to consider the possibility that the current update operation is actually changing some of the properties that are in the selector. So if validating `{$set: {type: 'variant', name: 'foo'}}`, where `doc.type` is currently "simple" in the database, which schema does it use?

**Comment by newsiberian** [comment]
Hello, I will describe changes tomorrow. There are still work in progress I guess.

I can't find a way to run tests on `core` with new packages structure. Could you please give me a tip?

**Comment by newsiberian** [comment]
Hi, I changed API like you said. Now you could add schemas like so:
```javascript
products = new Mongo.Collection("Products");
products.attachSchema(Product, { selector: { type: 'simple' } });
products.attachSchema(ProductVariant, { selector: { type: 'variant' } });
```
Instead of `collection.simpleSchema().clean(object)` we have to call:
`collection.simpleSchema(object, { selector: { type: 'simple' } }).clean(object);`

Seems like `newContext()` functionality could not be used with such schema structure.

> Another problem with this is that you don't currently handle the case where we're validating a modifier.

I did some changes in this direction. Is it now covered?

> I think we'd have to add in a `findOne` to get the current document and check it against the selector. But then it would also have to consider the possibility that the current update operation is actually changing some of the properties that are in the selector.

I play with it [here](https://github.com/newsiberian/meteor-collection2-core/blob/flattened/lib/collection2.js#L211-L224), but I can't see a use case for that. If developer consider to change schema for `doc` by `$set`ing new `selector`, he should do some extra job to remove old fields from `doc` within collection. I think we should leave this to developer to prepare his doc for a new schema.

> So if validating {$set: {type: 'variant', name: 'foo'}}, where doc.type is currently "simple" in the database, which schema does it use?

Schema "simple" will be used and it will be validated only those fields which is in `$set` right now. Other fields which is in database doc - developer should change manually - remove or update. I believe.

Why? changing schema is not ordinary step, so if developer do that, he could pass all fields he need in '$set' and after that - removes other.

**Comment by newsiberian** [comment]
Hello, @aldeed, I did some changes to this PR. Also, I've worked with this branch for some time and it works fine for me.
## New API

Let's say our `selector` will be field «type» and type will be «simple» or «variant». We have several ways to pass `selector` to `simpleSchema`.

#### attach schema to collection
`MyCollection.attachSchema(Product, {selector: {type: 'simple'}});`
`MyCollection.attachSchema(Variant, {selector: {type: 'variant'}});`

Where Product and Variant are two separate schemas.

#### insert
* 1st way is by sending selector inside <query>:
`MyCollection.insert({ title: 'This is a product', type: 'simple'});`

*2st way is by sending selector like an option:
`MyCollection.insert({ title: 'This is a product' }, { selector: { type: 'simple' } });`

#### update/upsert
`upsert` examples is similar.

* 1st way is to put selector inside <query>:
```javascript
MyCollection.update(
  {
    title: 'This is a product', type: 'simple'
  }, {
    $set: { description: 'This is a modified product.' }
  }
);
```

* 2nd way is to put selector in <udpate>:
```javascript
MyCollection.update(
  { title: 'Product one' },
  { $set: {
    description: 'This is a modified product.',
    type: 'simple' // selector in <update>
  }}
);
```

* 3rd way: send selector as an <option>:
```javascript
MyCollection.update(
  { title: 'Product one', type: 'simple' },
  { $set: {
    description: 'This is a modified product three.'
  } },
  { selector: { type: 'simple' } }
);
```

#### Change document schema
You can change existing schema in two steps: first you'll need to update document with new `selector` and with new schema's fields. In second, you'll need to `$unset` old schema's fields which is not used anymore. Additionally you need to pass `validate: false` options, because these fields are not in your current schema.
```javascript
MyCollection.update(productId, {
  $set: {
    price: 10, // validating against new schema
    type: 'variant'
  }
}).update(productId, {
    $unset: { description: '' }
  }, {
    selector: { type: 'variant' },
    validate: false
  }
);
```

### Schema format
To work with multi-schema you need to specify the selector. You can do this by several ways:
* If `object` contains selector (it should because selector should be required)
`MyCollection.simpleSchema(object)`;

* And if `object` doesn't:
`MyCollection.simpleSchema(object, { selector: { field: 'value' } })`;

#### deny
Deny inserting or updating should work. At least they work in tests.

**Comment by aaronjudd** [comment]
@newsiberian do you know why the CI is failing for this?  @aldeed is there anything else we need to do to have this merged in the next release?

**Comment by newsiberian** [comment]
Tests will be successful with related `collection2-core` [package](https://github.com/aldeed/meteor-collection2-core/pull/1), because all logic is there

**Comment by aaronjudd** [comment]
@aldeed thanks!

**Comment by newsiberian** [comment]
@aldeed, thanks a lot)

**Comment by aldeed** [comment]
No problem, sorry for the delay. This is now published with c2 2.9.0 (c2-core 1.1.0) and I documented it in the readme.

**Pull request merged**
