### PR TITLE
Update raix:eventemitter

### PR DESCRIPTION
**Pull request by StorytellerCZ**
`raix:eventemitter` removed `underscore` from their package.

### CODE REVIEW

**Comment by macrozone** [comment]
@aldeed would be cool to get that in! that's the last usage of underscore in many projects as it seems!

**Comment by pozylon** [comment]
@aldeed @macrozone same here, if that pull request gets merged, I would get rid of underscore in at least 3 projects

**Comment by morloy** [comment]
Please merge 👍

**Comment by rcsandell** [comment]
a79d4533444e890e60ed179309345c1a4cf7f7bc

**Pull request closed without merging**
