### PR TITLE
Update Readme.md - Heartbeat

### PR DESCRIPTION
**Pull request by mryraghi**
This is the problem I had: "Exception in setInterval callback: Error: heartbeat is not allowed by the schema". By adding the following lines of code everything seems working properly!

### CODE REVIEW

**Comment by aldeed** [comment]
Are you sure this is part of the core Meteor user schema? It seems like something a package you're using might be adding. We don't need to document all custom properties that any package might add, but if it's a really common package, it would be OK to document it.

**Comment by mryraghi** [comment]
The packages that I'm using and that could affect collection2 schema are only *account-password* and *roles*. It's up to you of course, but it could be useful for newbies!

**Comment by aldeed** [comment]
I don't mind adding it, but it would be best to have a comment explaining under what circumstances it's needed. I don't see anything in the Meteor repo when searching for `heartbeat`. It would be nice to figure out what is adding it.

**Comment by mryraghi** [comment]
You are perfectly right. There aren't many information about heartbeats but I discovered that Meteor relies on Sockjs' heartbeats to keep connections alive (https://meteor.hackpad.com/DDP-Heartbeats-jdQy4zGB4Bx).
screen shot 2015-11-02 at 14 47 38
After you log in with *account-password* and after a couple of minutes of inactivity (same thing if you close the tab/window) a *heartbeat* entry appears as a property of the current user logged in.

**Pull request merged**
